[loadbalancers]
lb-node-1 ansible_host=192.168.122.11 keepalived_role=MASTER priority=101
lb-node-2 ansible_host=192.168.122.12 keepalived_role=BACKUP priority=100

[webservers]
backend-1 ansible_host=192.168.122.21 server_name=Backend-Server-01
backend-2 ansible_host=192.168.122.22 server_name=Backend-Server-02

[all:vars]
ansible_user=ubuntu
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
virtual_ip=192.168.122.100/24
network_interface=eth0